# 必要な環境変数を設定してください
export DEBUG=
export DJANGO_SETTINGS_MODULE=
export DJANGO_PORT=
export DB_NAME=
export DB_USER=
export DB_PASSWORD=
export DB_HOST=
export DB_PORT=
export SECRET_KEY=
export LANG=
export TWITTER_CONSUMER_KEY=
export TWITTER_CONSUMER_SECRET=
export FACEBOOK_APP_ID=
export FACEBOOK_API_SECRET=
export NEW_RELIC_CONFIG_FILE=
